import re
import csv
import pandas as pd
import matplotlib.pyplot as plt

# snakemake --jobs 50 --cluster "sbatch --mem-per-cpu=10g --nodes=1 --ntasks={threads} --time=00:30:00 --extra-node-info=1:*:1 --distribution=*:block:* --mem-bind=local"
# 

# MPI benchmarking configurations
#N_VALUES = [2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,28,29,30,31,32]
N_VALUES = [2,3,4,5,7,10,12,16,20,24,32]
REPEATS = range(0,6)
HOSTS = ["milan", "genoa"]

# -----------------------------
# Top-level workflow
# -----------------------------
rule all:
    input:
        "results/speedup.png"

# -----------------------------
# Run MPI jobs (submitted to Slurm)
# -----------------------------
rule run_mpi:
    output:
        "results/run_{n}_{r}_{h}.out"
    params:
        exe="../../bin/seapodym_cohort",
        parfile="skj_fat.xml"
    threads:
        lambda wc: int(wc.n)
    shell:
        r"""
        cd ~/seapodym_scaling/seapodym-codebase-phase3/
        source sourceme.sh
        cd example-configs/density_skj_fat
        mkdir -p results
        # record SLURM job ID
        echo "jobid=$SLURM_JOB_ID" > {output}
        # run MPI program using Slurm
        srun {params.exe} -s {params.parfile} >> {output} 2>&1
        """

# -----------------------------
# Collect results into CSV
# -----------------------------
rule collect_results:
    input:
        expand("results/run_{n}_{r}_{h}.out", n=N_VALUES, r=REPEATS, h=HOSTS)
    output:
        "results/timings.csv"
    run:
        pattern = re.compile(r"time manager\s*=\s*([0-9.]+)")
        rows = []

        for f in input:
            parts = f.split("/")[-1].replace(".out","").split("_")
            n = int(parts[1])
            r = int(parts[2])
            host = parts[3]

            jobid = None
            manager_time = None

            with open(f) as fh:
                for line in fh:
                    if line.startswith("jobid="):
                        jobid = line.split("=")[1].strip()
                    m = pattern.search(line)
                    if m:
                        manager_time = float(m.group(1))

            rows.append((n, jobid, host, manager_time))

        rows.sort()

        with open(output[0], "w", newline="") as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(["nprocs","jobid","host","manager_time"])
            writer.writerows(rows)

# -----------------------------
# Plot speedup
# -----------------------------
rule plot_speedup:
    input:
        "results/timings.csv"
    output:
        "results/speedup.png"
    shell:
    	r"""
    	ml purge
    	ml Python
    	python plot_scaling.py -i {input} -o {output}
    	"""

