import re
import csv
import pandas as pd
import matplotlib.pyplot as plt

# snakemake --jobs 10 --cluster "sbatch -p genoa --mem=50g --nodes=1 --ntasks-per-node={threads} --cpus-per-task=1 --time=01:30:00 --extra-node-info=1:*:1 --distribution=*:block:* --mem-bind=local"
# 

# MPI benchmarking configurations
PROCS = [3, 10, 20, 30, 40, 50, 70, 100]
REPEATS = range(0,3)
HOSTS = ["genoa",]
CASES = ["aplus", "aplus3"]

# -----------------------------
# Top-level workflow
# -----------------------------
rule all:
    input:
        "results/timings.csv"

# -----------------------------
# Run MPI jobs (submitted to Slurm)
# -----------------------------
rule run_mpi:
    output:
        exp="results/run_{n}_{r}_{h}_{c}.out",
    params:
        parfile="skj_Fat.xml"
    threads:
        lambda wc: int(wc.n)
    shell:
        r"""
        set -x
        cd ~/nesi99999/seapodym-codebase-exp/
        
        source sourceme-exp.sh

        cd example-configs/density_skj_fat
        mkdir -p results
        # create a tmp directory to run at the same level
        cd ..
        hash=$(echo "$RANDOM" | sha256sum | cut -d' ' -f1)
        rundir="tmp-$hash"
        rm -rf $rundir
        mkdir $rundir
        cd $rundir
        # copy the input file
        cp ../density_skj_fat/{params.parfile} .


        # run 
        echo "jobid=$SLURM_JOB_ID" > ../density_skj_fat/{output.exp}
        srun --ntasks={threads} --distribution=block:block --cpu-bind=cores --cpus-per-task=1 \
             ../../bin/seapodym_cohort_{wildcards.c} -s {params.parfile} >> ../density_skj_fat/{output.exp} 2>&1

        cd ../
        # clean up
        rm -rf $rundir
        # back to where we started
        cd density_skj_fat
        """

# -----------------------------
# Collect results into CSV
# -----------------------------
rule collect_results:
    input:
        expand("results/run_{n}_{r}_{h}_{c}.out", n=PROCS, r=REPEATS, h=HOSTS, c=CASES),
    output:
        "results/timings.csv"
    shell:
        r"""
        module load Python
        python assemble_timings_aplus.py -d results -o results/timings.csv
        """

